In [32]:
import numpy as np
import time

In [7]:
##1
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
##1.2
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
##2
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [12]:
##2.1
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
##3
x = np.random.uniform(10,99,20)
x = x**2
x

array([ 841.33316883,  457.34698666, 2071.94746208,  422.47259706,
       4846.70554958,  914.7239568 ,  112.46929403,  116.75831133,
       2001.21962741, 7721.33703572,  844.64186379, 6645.38740534,
       4622.15780083, 1549.59136389, 9601.11954602, 7532.59114061,
       7534.16534446, 1717.4941346 ,  431.66838532,  909.49364706])

In [30]:
##4
x = np.random.uniform(10,99,20)
lc = [i**2 for i in x]


[973.5584048366027,
 293.24229446743254,
 2063.8996016287397,
 576.3547443508628,
 2209.1436215477424,
 114.09642601358863,
 3415.0115668009903,
 4077.765070965352,
 1467.42020579285,
 1008.4007807118974,
 7641.2269257846565,
 1973.8702155987792,
 2334.02488646193,
 109.82778565059019,
 2845.386133955826,
 9395.051260337144,
 8044.882867644866,
 106.0058149100284,
 3130.0443342218177,
 9202.813540803298]

In [33]:
##5
time.time()
x = np.random.uniform(10,99,20)
x = x**2
time.time()

1596021574.7417557

In [34]:
#5.1
time.time()
x = np.random.uniform(10,99,20)
lc = [i**2 for i in x]
time.time()

1596021615.3895059

In [ ]:
##6
x = np.arange(10, 1000)
x

In [ ]:
##7
x = np.arange(10,200,2)
x

In [ ]:
##8
x = np.arange(13,900,2)
x

In [ ]:
##9
x = np.eye(4)
x

In [ ]:
##10
x = np.random.randint(5,25,100)
print(x)
np.diff(x)

In [ ]:
##11
x = np.linspace(0,1,5)
x

In [ ]:
##12
y = np.random.randint(50,100,(4,4))
print(y)
y.T

In [62]:
##Array
xq = np.arange(1,26)
xq = xq.reshape(5,5)
xq

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
##13
xq[1:3,2:4]

In [ ]:
##14
xq[3,2:5]

In [ ]:
##15
xq[3:5,0:2]

In [73]:
##16
xq[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
##17
xq = np.arange(1,26)
xq = xq.reshape(5,5)
xq

In [129]:
##18
y = []
x = np.random.randint(10,100,(5,5))
print(x)
for i in x :
  for o in i :
    if o > 50 :
      y.append(o)
print(y)

[[67 82 66 28 66]
 [77 89 17 44 30]
 [49 40 22 15 41]
 [46 72 95 25 39]
 [72 29 89 99 29]]
11


In [85]:
##19
cn = []
x = np.random.randint(10,100,(5,5))
cn.append(x[x > 40])
cn

[array([56, 45, 97, 46, 97, 83, 84, 62, 86, 72, 91, 85, 89, 68, 73])]

In [88]:
##20
cn = []
count = 0
while count != 9 :
  numbers = int(input('Enter Any Number(10-100)'))
  cn.append(numbers)
  count += 1
print(cn)

arr = np.array(cn)


Enter Any Number(10-100)23
Enter Any Number(10-100)45
Enter Any Number(10-100)12
Enter Any Number(10-100)23
Enter Any Number(10-100)67
Enter Any Number(10-100)89
Enter Any Number(10-100)54
Enter Any Number(10-100)32
Enter Any Number(10-100)21
[23, 45, 12, 23, 67, 89, 54, 32, 21]
[23 45 12 23 67 89 54 32 21]


array([23, 45, 12, 23, 67, 89, 54, 32, 21])

In [92]:
##20 ต่อ
arr = arr.reshape(3,3)
print(arr)
arr.T
arr[2,2]

[[23 45 12]
 [23 67 89]
 [54 32 21]]


21